#!/bin/sh

# gnome
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark

# vscode
jq '.["workbench.colorTheme"] = "Default Dark+"' '.config/Code - OSS/User/settings.json' > '.config/Code - OSS/User/settings.json~'
mv '.config/Code - OSS/User/settings.json~' '.config/Code - OSS/User/settings.json'

# alacritty
npx -y alacritty-themes Default.dark
