#!/bin/sh

# gtk
gsettings set org.gnome.desktop.interface color-scheme 'default'

# vscode
jq '.["workbench.colorTheme"] = "Default Light+"' '.config/Code - OSS/User/settings.json' > '.config/Code - OSS/User/settings.json~'
mv '.config/Code - OSS/User/settings.json~' '.config/Code - OSS/User/settings.json'

#alacritty
npx -y alacritty-themes Default.light
