#!/bin/sh

export OUTPUT=$(swaymsg -t get_outputs --raw | jq --raw-output '.[] | select(.focused).name')
swaymsg input type:tablet_tool map_to_output $OUTPUT

swaymsg -t subscribe -m '["workspace"]' |
while read EVENT
do
	echo $EVENT |
	jq --raw-output 'select(.change=="focus").current.output' |
	while read OUTPUT
	do
		swaymsg input type:tablet_tool map_to_output $OUTPUT
	done
done

