#!/bin/sh

OUTPUT=$(swaymsg --type get_outputs --raw | jq --raw-output '.[] | select(.focused).name')
swaymsg input type:tablet_tool map_to_output $OUTPUT

swaymsg --type subscribe --monitor '["workspace"]' |
while read EVENT
do
	OUTPUT=$(swaymsg --type get_outputs --raw | jq --raw-output '.[] | select(.focused).name')
	swaymsg input type:tablet_tool map_to_output $OUTPUT
done
